# Generated by Django 4.2.1 on 2023-05-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0002_service_carmodel_year_orderentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['date', 'id'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='sum',
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='autoservisas.order', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='quantity',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Kiekis'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='autoservisas.service', verbose_name='service'),
        ),
    ]
