# Generated by Django 4.2.1 on 2023-06-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0006_remove_order_status_orderentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='autoservisas/car_covers', verbose_name='cover'),
        ),
    ]
