# Generated by Django 4.2.1 on 2023-06-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0009_remove_service_status_orderentry_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['license_plate'], 'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='client',
        ),
        migrations.AddField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due back'),
        ),
    ]
