# Generated by Django 4.2.1 on 2023-06-06 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoservisas', '0011_car_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='client',
        ),
        migrations.AddField(
            model_name='car',
            name='due_back',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Due back'),
        ),
        migrations.AddField(
            model_name='car',
            name='user_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL, verbose_name='user_field'),
        ),
    ]
