# Generated by Django 4.2.1 on 2023-06-06 17:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0012_remove_car_client_car_due_back_car_user_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['model', 'license_plate'], 'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.RemoveField(
            model_name='car',
            name='due_back',
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=10000, null=True, verbose_name='Description'),
        ),
    ]
