# Generated by Django 4.2.1 on 2023-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservisas', '0014_remove_car_user_field_car_client_userorderreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, null=True, verbose_name='Price'),
        ),
    ]
